version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: ebengkel-postgresql
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ebengkel-postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  redis:
    image: redis:latest
    container_name: ebengkel-redis
    restart: always
    volumes:
      - ebengkel-redis:/data
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: ebengkel-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  ebengkel-postgresql:
    external: true
  ebengkel-redis:
    external: true
